---
- name: deploy the customized spark log4j properties
  template:
    src: "{{ log4j_template_file }}.j2"
    dest: "{{spark_usr_parent_dir}}/spark-{{spark_version}}/conf/{{ log4j_template_file }}"
    owner: "{{ spark_user }}"
    group: "{{ spark_user }}"
