---
  - name: deploy the customized spark log4j properties
    template:
      src: "{{ log4j_template_file }}.j2"
      dest: "{{ spark_conf_dir_orig }}/{{ log4j_template_file }}"
      owner: "{{ spark_user }}"
      group: "{{ spark_user }}"
