---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    ignore-certs: True
#    ignore-errors: True

driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7001
    image: centos:7
  - name: xenial001
    image: solita/ubuntu-systemd:16.04
    command: /sbin/init
    privileged: True
    # groups only required once we set up a mini cluster with spark services
    #groups:
    #  - spark_master

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        #TODO fix issues when trying to deploy the JDK using role(dependency) azavea.java
        #spark_install_java: yes
        spark_install_java: no
        spark_version: "2.1.1-bin-hadoop2.7"
        # following is set to ensure SPARK_LOCAL_DIRS is set in spark-env.sh
        spark_local_dirs: ["/tmp"]
        # Test spark-services later
        #spark_services_install_enabled: False
  lint:
    name: ansible-lint

scenario:
  name: default
  # Disabled some of the stages (for ex. 'lint' would throw many errors)
  test_sequence:
    - destroy
    - dependency
    - syntax
#    - lint
    - create
    - converge
    - idempotence
    - verify

verifier:
  name: testinfra
  lint:
    name: flake8
